# Generated by Django 3.2.5 on 2021-08-02 08:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage_cell_product_relationship',
            name='product',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='关联零件', on_delete=django.db.models.deletion.CASCADE, related_name='cells_related', to='warehouse.product_info'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage_cell_product_relationship',
            name='storage_cell',
            field=models.ForeignKey(help_text='关联储位', on_delete=django.db.models.deletion.CASCADE, related_name='products_related', related_query_name='product_infos', to='warehouse.storage_cell_info'),
        ),
    ]
