# Generated by Django 3.2.5 on 2021-08-10 07:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_auto_20210802_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storage_cell_product_relationship',
            old_name='number',
            new_name='occupy',
        ),
        migrations.RemoveField(
            model_name='entry_info',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='entry_info',
            name='number',
        ),
        migrations.RemoveField(
            model_name='entry_info',
            name='product',
        ),
        migrations.RemoveField(
            model_name='measure_plan_info',
            name='entry_info',
        ),
        migrations.RemoveField(
            model_name='measure_plan_info',
            name='product',
        ),
        migrations.RemoveField(
            model_name='measure_plan_info',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shipment_info',
            name='cell',
        ),
        migrations.RemoveField(
            model_name='shipment_info',
            name='number',
        ),
        migrations.RemoveField(
            model_name='shipment_info',
            name='product',
        ),
        migrations.AddField(
            model_name='measure_plan_info',
            name='description',
            field=models.CharField(help_text='批注', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='measure_plan_info',
            name='relationship_info',
            field=models.ForeignKey(default=None, help_text='关联产品储位信息', on_delete=django.db.models.deletion.CASCADE, related_name='measure_plan', to='warehouse.storage_cell_product_relationship'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse_info',
            name='capacity',
            field=models.IntegerField(default=0, help_text='容量', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehouse_info',
            name='occupy',
            field=models.IntegerField(default=0, help_text='占用', validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storage_cell_product_relationship',
            name='time',
            field=models.DateTimeField(help_text='更新时间'),
        ),
        migrations.CreateModel(
            name='shipment_product_relationship',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='出库数量', validators=[django.core.validators.MinValueValidator(0)])),
                ('entry', models.ForeignKey(help_text='关联出库单', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.shipment_info')),
                ('product', models.ForeignKey(help_text='零件', on_delete=django.db.models.deletion.CASCADE, to='warehouse.product_info')),
            ],
        ),
        migrations.CreateModel(
            name='main_board',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True, help_text='统计日期')),
                ('store_batches', models.IntegerField(help_text='入库批数', validators=[django.core.validators.MinValueValidator(0)])),
                ('store_amount', models.IntegerField(help_text='入库数量', validators=[django.core.validators.MinValueValidator(0)])),
                ('store_money', models.IntegerField(help_text='入库金额', validators=[django.core.validators.MinValueValidator(0)])),
                ('deliver_batches', models.IntegerField(help_text='出库批数', validators=[django.core.validators.MinValueValidator(0)])),
                ('deliver_amount', models.IntegerField(help_text='出库数量', validators=[django.core.validators.MinValueValidator(0)])),
                ('deliver_money', models.IntegerField(help_text='出库金额', validators=[django.core.validators.MinValueValidator(0)])),
                ('occupation', models.FloatField(help_text='仓库占用情况', validators=[django.core.validators.MinValueValidator(0)])),
                ('warehouse', models.ForeignKey(help_text='关联仓库', on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='warehouse.warehouse_info')),
            ],
        ),
        migrations.CreateModel(
            name='entry_product_relationship',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='入库数量', validators=[django.core.validators.MinValueValidator(0)])),
                ('entry', models.ForeignKey(help_text='关联入库单', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='warehouse.entry_info')),
                ('product', models.ForeignKey(help_text='零件', on_delete=django.db.models.deletion.CASCADE, to='warehouse.product_info')),
            ],
        ),
    ]
