# Generated by Django 3.2.5 on 2021-08-11 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210810_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_board',
            name='deliver_amount',
            field=models.IntegerField(default=0, help_text='出库数量', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='deliver_batches',
            field=models.IntegerField(default=0, help_text='出库批数', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='deliver_money',
            field=models.IntegerField(default=0, help_text='出库金额', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='occupation',
            field=models.FloatField(default=0, help_text='仓库占用情况', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='store_amount',
            field=models.IntegerField(default=0, help_text='入库数量', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='store_batches',
            field=models.IntegerField(default=0, help_text='入库批数', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='main_board',
            name='store_money',
            field=models.IntegerField(default=0, help_text='入库金额', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
