# Generated by Django 3.2.5 on 2021-08-16 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_auto_20210811_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure_plan_info',
            name='relationship_info',
            field=models.OneToOneField(help_text='关联产品储位信息', on_delete=django.db.models.deletion.CASCADE, related_name='measure_plan', to='warehouse.storage_cell_product_relationship'),
        ),
    ]
