# Generated by Django 3.1.5 on 2021-07-13 15:34

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_account_info',
            fields=[
                ('uid', models.CharField(help_text='用户编号', max_length=11, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(11)])),
                ('name', models.CharField(help_text='用户名称', max_length=60, unique=True)),
                ('password_hash', models.CharField(help_text='用户密码哈希值', max_length=60)),
                ('role', models.IntegerField(choices=[(0, 'admin'), (1, 'super_editor'), (2, 'viewer')], help_text='权限角色')),
                ('role_warehouse', models.IntegerField(choices=[(0, 'admin'), (1, 'super_editor'), (2, 'viewer')], help_text='仓储权限角色')),
            ],
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user', models.OneToOneField(help_text='用户信息', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_info', serialize=False, to='user.user_account_info')),
                ('fullname', models.CharField(help_text='用户全名', max_length=60, null=True)),
                ('email', models.CharField(help_text='用户email', max_length=60, null=True)),
                ('phone', models.CharField(help_text='用户手机', max_length=60, null=True)),
                ('work_id', models.CharField(help_text='用户工号', max_length=60, null=True)),
                ('avatar', models.CharField(help_text='图片地址', max_length=256, null=True)),
            ],
        ),
    ]
